// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMg4ENnK39QUXDeiMBEn-ie_StIIi5A7U',
    appId: '1:1046288277252:web:b2ea360b5487c3631e3a51',
    messagingSenderId: '1046288277252',
    projectId: 'simple-log-in-2ee31',
    authDomain: 'simple-log-in-2ee31.firebaseapp.com',
    storageBucket: 'simple-log-in-2ee31.appspot.com',
    measurementId: 'G-3Q2WMTET2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRONDP_sApS4UKU2yy9tmlbrOIWxlzCc',
    appId: '1:1046288277252:android:d352db9d027b77a11e3a51',
    messagingSenderId: '1046288277252',
    projectId: 'simple-log-in-2ee31',
    storageBucket: 'simple-log-in-2ee31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChxcvAqraZReJSXrvgwxZ-1p5wVqVEicU',
    appId: '1:1046288277252:ios:353143e0fbe52bc71e3a51',
    messagingSenderId: '1046288277252',
    projectId: 'simple-log-in-2ee31',
    storageBucket: 'simple-log-in-2ee31.appspot.com',
    androidClientId: '1046288277252-030deeqbp4srvr2mch5gfenej88off8u.apps.googleusercontent.com',
    iosClientId: '1046288277252-cs4nctee3b80fb6dqhtrspm6i1olf9g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChxcvAqraZReJSXrvgwxZ-1p5wVqVEicU',
    appId: '1:1046288277252:ios:353143e0fbe52bc71e3a51',
    messagingSenderId: '1046288277252',
    projectId: 'simple-log-in-2ee31',
    storageBucket: 'simple-log-in-2ee31.appspot.com',
    androidClientId: '1046288277252-030deeqbp4srvr2mch5gfenej88off8u.apps.googleusercontent.com',
    iosClientId: '1046288277252-cs4nctee3b80fb6dqhtrspm6i1olf9g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );
}
